# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    desc "Generate app icon"
    lane :app_icon do
        appicon(
            appicon_image_file: 'fastlane/metadata/app_icon.png',
            appicon_devices: [:ipad, :iphone, :ios_marketing],
            appicon_path: "OpenArchive/Assets.xcassets"
        )
    end
end
