# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iOS 13.1 @ iPhone 11 Pro Max",
  "iOS 13.1 @ iPhone 8 Plus",
  "iOS 13.1 @ iPad Pro (12.9-inch) (2nd generation)",
  "iOS 13.1 @ iPad Pro (12.9-inch) (3rd generation)",
])

languages([
  "en-US",
  "de-DE",
  "fr-FR",
  "es-MX",
  "ru",
  "tr",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme("Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot

output_simulator_logs(true)
# reinstall_app(true)
clean(true)
stop_after_first_error(true)
concurrent_simulators(false)
